import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { ASSETS_DIR } from '../assets.js';
import { renderTemplate } from '../lib/template.js';
import { JSON_SCHEMAS, toJsonSchema } from '../schemas/index.js';
import { stripItems } from './skeleton.js';

/**
 * Ownership policy of an installed file.
 * - framework: owned by alterspec; `update` replaces it.
 * - wrapper:   alterspec's `.claude/` wrappers; `update` replaces them unless the user modified them.
 * - user:      written once if missing, then never touched again.
 */
export type Policy = 'framework' | 'wrapper' | 'user';

export interface PlannedFile {
  /** Path relative to the project root, with forward slashes. */
  path: string;
  content: string;
  policy: Policy;
}

export interface PlanContext {
  appName: string;
  version: string;
}

const toPosix = (p: string) => p.split(sep).join('/');

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/** Every asset file under a sub-directory, as [relative path, content]. */
function assetFiles(sub: string): [string, string][] {
  const base = join(ASSETS_DIR, sub);
  return walk(base)
    .sort()
    .map((f) => [toPosix(relative(base, f)), readFileSync(f, 'utf8')]);
}

const readAsset = (p: string) => readFileSync(join(ASSETS_DIR, p), 'utf8');

/** Collection templates become empty files in the skeleton; prose templates are copied as they are. */
const SKELETON_APPLICATION: Record<string, 'strip' | 'copy'> = {
  'personas-roles.md': 'strip',
  'glossary.md': 'strip',
  'rules.md': 'strip',
  'events.md': 'strip',
  'decisions.md': 'strip',
  'integrations.md': 'strip',
  'nfr.md': 'copy',
};

const GENERATED_README = `# Generated views

Everything in this folder is generated by \`alterspec views\` and \`alterspec validate\`.
Never edit these files by hand; your changes would be overwritten.
`;

const CUSTOM_README = `# Custom overrides

This folder is yours. \`alterspec update\` never touches it.

- \`custom/prompts/<command>.md\` replaces \`.alterspec/prompts/<command>.md\` for that command.
- \`custom/prompts/agents/<agent>.md\` replaces the prompt of an alterspec agent.
- \`custom/templates/<name>.md\` replaces a template in \`.alterspec/templates/\`.

Copy the original file here first, then edit the copy.
`;

/** Everything `alterspec init` / `update` installs, with its ownership policy. */
export function buildPlan(ctx: PlanContext): PlannedFile[] {
  const files: PlannedFile[] = [];
  const add = (path: string, content: string, policy: Policy) => files.push({ path, content, policy });

  // .alterspec/ — framework-owned
  for (const [p, c] of assetFiles('templates')) add(`.alterspec/templates/${p}`, c, 'framework');
  for (const [p, c] of assetFiles('prompts')) add(`.alterspec/prompts/${p}`, c, 'framework');
  for (const [name, schema] of Object.entries(JSON_SCHEMAS)) {
    add(
      `.alterspec/schemas/${name}.schema.json`,
      JSON.stringify(toJsonSchema(name, schema), null, 2) + '\n',
      'framework',
    );
  }
  add('.alterspec/version', `${ctx.version}\n`, 'framework');

  // .alterspec/ — user-owned once created
  add('.alterspec/config.yaml', renderTemplate(readAsset('config.yaml'), { version: ctx.version }), 'user');
  add('.alterspec/custom/README.md', CUSTOM_README, 'user');

  // .claude/ — thin wrappers
  for (const [p, c] of assetFiles('claude')) add(`.claude/${p}`, c, 'wrapper');

  // spec/ — user-owned skeleton
  add(
    'spec/application/application.md',
    renderTemplate(readAsset('templates/application.md'), { app_name: ctx.appName }),
    'user',
  );
  for (const [name, how] of Object.entries(SKELETON_APPLICATION)) {
    const tpl = readAsset(`templates/${name}`);
    add(`spec/application/${name}`, how === 'strip' ? stripItems(tpl) : tpl, 'user');
  }
  for (const dir of ['application/entities', 'application/flows', 'modules', 'changes/archive']) {
    add(`spec/${dir}/.gitkeep`, '', 'user');
  }
  add('spec/_generated/README.md', GENERATED_README, 'user');

  return files;
}
