import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ASSETS_DIR } from '../assets.js';
import type { SpecModel } from '../spec/model.js';
import { blockHash } from '../views/blocks.js';
import { pageFile, renderPages } from './render.js';
import { buildWireframe, type WireframeModel, type ScreenPage } from './model.js';

/** Where `alterspec views` writes the generic wireframe, relative to spec/. */
export const WIREFRAME_DIR = '_generated/wireframe';
/** Where versions before 0.6 wrote it; `views` removes what is left there. */
export const LEGACY_WIREFRAME_DIR = '_generated/prototype/';
export const MANIFEST_FILE = 'manifest.json';

export interface WireframeManifest {
  /** Fingerprint of the whole page model; variants record it to detect that they are stale. */
  hash: string;
  screens: Record<
    string,
    { file: string; hash: string; elements: string[]; roles: Record<string, string[]> }
  >;
}

/** Every `data-src` marker a page for this screen must carry, sorted. */
export function expectedElements(s: ScreenPage): string[] {
  return [
    ...new Set([
      s.src,
      ...s.roles.map((r) => r.src),
      ...s.entryPoints.map((e) => e.src),
      ...s.gaps.map((g) => g.src),
      ...s.states.map((x) => x.src),
      ...s.actions.map((a) => a.src),
      ...s.groups.flatMap((g) => [g.src, ...g.fields.map((f) => f.src)]),
    ]),
  ].sort();
}

/** Who sees each element: groups, fields and actions their own roles, everything else the screen's roles. */
export function elementRoles(s: ScreenPage): Record<string, string[]> {
  const screen = [...s.roles.map((r) => r.id)].sort();
  const out: Record<string, string[]> = {};
  for (const e of expectedElements(s)) out[e] = screen;
  for (const r of s.roles) delete out[r.src];
  for (const g of s.groups) for (const e of [g.src, ...g.fields.map((f) => f.src)]) out[e] = g.roles;
  for (const a of s.actions) out[a.src] = a.roles;
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => (a < b ? -1 : 1)));
}

const unescape = (s: string) =>
  s
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');

/** The `data-src` markers found in a page, sorted and unique. */
export function collectElements(html: string): string[] {
  return [...new Set([...html.matchAll(/\sdata-src="([^"]*)"/g)].map((m) => unescape(m[1]!)))].sort();
}

export function buildManifest(m: WireframeModel): WireframeManifest {
  return {
    hash: blockHash(JSON.stringify(m)),
    screens: Object.fromEntries(
      m.screens.map((s) => [
        s.id,
        {
          file: pageFile(s.id),
          hash: blockHash(JSON.stringify(s)),
          elements: expectedElements(s),
          roles: elementRoles(s),
        },
      ]),
    ),
  };
}

export const asset = (name: string) => readFileSync(join(ASSETS_DIR, 'wireframe', name), 'utf8');

export const GENERATED_HTML =
  '<!-- Generated by `alterspec views` from the spec. Do not edit: change the spec and run `alterspec views`. -->';

/** The generic wireframe of some screens only (for a handoff), keyed by file name. */
export function scopedWireframe(model: SpecModel, screenIds: string[], banner: string): Map<string, string> {
  const keep = new Set(screenIds);
  const full = buildWireframe(model);
  const m: WireframeModel = {
    ...full,
    screens: full.screens.filter((s) => keep.has(s.id)),
    modules: full.modules
      .map((mod) => ({ ...mod, screens: mod.screens.filter((s) => keep.has(s.id)) }))
      .filter((mod) => mod.screens.length > 0),
  };
  m.roles = full.roles.filter((r) => m.screens.some((s) => s.roles.some((x) => x.id === r.id)));
  const out = renderPages(m, { banner });
  out.set('base.css', asset('generic/base.css'));
  out.set('state.css', asset('state.css'));
  out.set('app.js', asset('app.js'));
  return out;
}

/** The generic wireframe files, keyed by path relative to spec/. */
export function planWireframe(model: SpecModel): Map<string, string> {
  const m = buildWireframe(model);
  const out = new Map<string, string>();
  const put = (name: string, content: string) => out.set(`${WIREFRAME_DIR}/${name}`, content);
  for (const [name, html] of renderPages(m, { banner: GENERATED_HTML })) put(name, html);
  put('base.css', asset('generic/base.css'));
  put('state.css', asset('state.css'));
  put('app.js', asset('app.js'));
  put(MANIFEST_FILE, JSON.stringify(buildManifest(m), null, 2) + '\n');
  return out;
}
