import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ASSETS_DIR } from '../assets.js';
import type { SpecModel } from '../spec/model.js';
import { blockHash } from '../views/blocks.js';
import { pageFile, renderPages } from './render.js';
import { GENERIC } from './skins/generic.js';
import { buildPrototype, type PrototypeModel, type ScreenPage } from './model.js';

/** Where `alterspec views` writes the generic prototype, relative to spec/. */
export const PROTOTYPE_DIR = '_generated/prototype';
export const MANIFEST_FILE = 'manifest.json';

export interface PrototypeManifest {
  /** Fingerprint of the whole page model; variants record it to detect that they are stale. */
  hash: string;
  screens: Record<string, { file: string; hash: string; elements: string[] }>;
}

/** Every `data-src` marker a page for this screen must carry, sorted. */
export function expectedElements(s: ScreenPage): string[] {
  return [
    ...new Set([
      s.src,
      ...s.roles.map((r) => r.src),
      ...s.entryPoints.map((e) => e.src),
      ...s.gaps.map((g) => g.src),
      ...s.states.map((x) => x.src),
      ...s.actions.map((a) => a.src),
      ...s.groups.flatMap((g) => [g.src, ...g.fields.map((f) => f.src)]),
    ]),
  ].sort();
}

const unescape = (s: string) =>
  s
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');

/** The `data-src` markers found in a page, sorted and unique. */
export function collectElements(html: string): string[] {
  return [...new Set([...html.matchAll(/\sdata-src="([^"]*)"/g)].map((m) => unescape(m[1]!)))].sort();
}

export function buildManifest(m: PrototypeModel): PrototypeManifest {
  return {
    hash: blockHash(JSON.stringify(m)),
    screens: Object.fromEntries(
      m.screens.map((s) => [
        s.id,
        { file: pageFile(s.id), hash: blockHash(JSON.stringify(s)), elements: expectedElements(s) },
      ]),
    ),
  };
}

export const asset = (name: string) => readFileSync(join(ASSETS_DIR, 'prototype', name), 'utf8');

export const GENERATED_HTML =
  '<!-- Generated by `alterspec views` from the spec. Do not edit: change the spec and run `alterspec views`. -->';

/** The generic prototype of some screens only (for a handoff), keyed by file name. */
export function scopedPrototype(model: SpecModel, screenIds: string[], banner: string): Map<string, string> {
  const keep = new Set(screenIds);
  const full = buildPrototype(model);
  const m: PrototypeModel = {
    ...full,
    screens: full.screens.filter((s) => keep.has(s.id)),
    modules: full.modules
      .map((mod) => ({ ...mod, screens: mod.screens.filter((s) => keep.has(s.id)) }))
      .filter((mod) => mod.screens.length > 0),
  };
  m.roles = full.roles.filter((r) => m.screens.some((s) => s.roles.some((x) => x.id === r.id)));
  const out = renderPages(m, GENERIC, { banner });
  out.set('base.css', asset('generic/base.css'));
  out.set('state.css', asset('state.css'));
  out.set('app.js', asset('app.js'));
  return out;
}

/** The generic prototype files, keyed by path relative to spec/. */
export function planPrototype(model: SpecModel): Map<string, string> {
  const m = buildPrototype(model);
  const out = new Map<string, string>();
  const put = (name: string, content: string) => out.set(`${PROTOTYPE_DIR}/${name}`, content);
  for (const [name, html] of renderPages(m, GENERIC, { banner: GENERATED_HTML })) put(name, html);
  put('base.css', asset('generic/base.css'));
  put('state.css', asset('state.css'));
  put('app.js', asset('app.js'));
  put(MANIFEST_FILE, JSON.stringify(buildManifest(m), null, 2) + '\n');
  return out;
}
