import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import { parse } from 'yaml';
import { DesignSchema, type Design } from '../schemas/design.js';
import type { SpecModel } from '../spec/model.js';
import { asset, buildManifest, collectElements } from './index.js';
import { buildPrototype } from './model.js';
import { renderPages, type Skin } from './render.js';
import { bootstrapSkin, bootstrapTheme } from './skins/bootstrap.js';
import { tailwindSkin } from './skins/tailwind.js';

/** User-owned design folder and the variants folder, relative to the project root. */
export const DESIGN_DIR = 'design';
export const VARIANTS_DIR = 'prototype';
export const VARIANT_FILE = 'variant.json';
export const BUILT_VARIANTS = ['bootstrap', 'tabler', 'tailwind'] as const;
export type BuiltVariant = (typeof BUILT_VARIANTS)[number];

export const VARIANT_HTML =
  '<!-- Generated by `alterspec prototype build` from the spec and design/. Do not edit: change the spec or design/ and build again. -->';

export interface VariantStamp {
  variant: string;
  /** Hash of the generic prototype manifest the variant was built from. */
  manifest: string;
}

export class DesignError extends Error {}

export function readDesign(root: string): Design | undefined {
  const path = join(root, DESIGN_DIR, 'design.yaml');
  if (!existsSync(path)) return undefined;
  const r = DesignSchema.safeParse(parse(readFileSync(path, 'utf8')) ?? {});
  if (!r.success) {
    throw new DesignError(
      `${DESIGN_DIR}/design.yaml is invalid: ${r.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')}`,
    );
  }
  return r.data;
}

/** The files of one variant, keyed by path inside prototype/<variant>/. */
export function buildVariant(
  model: SpecModel,
  root: string,
  design: Design,
  variant: BuiltVariant,
): Map<string, string | Buffer> {
  const m = buildPrototype(model);
  const out = new Map<string, string | Buffer>();
  const tokens = join(root, DESIGN_DIR, 'tokens.css');
  const extra = existsSync(tokens) ? ['<link rel="stylesheet" href="tokens.css">'] : [];
  if (existsSync(tokens)) out.set('tokens.css', readFileSync(tokens));

  let logo: string | undefined;
  if (design.app.logo) {
    const p = join(root, DESIGN_DIR, design.app.logo);
    if (!existsSync(p)) throw new DesignError(`logo ${DESIGN_DIR}/${design.app.logo} does not exist`);
    logo = `assets/${basename(p)}`;
    out.set(logo, readFileSync(p));
  }

  let skin: Skin;
  if (variant === 'tailwind') skin = tailwindSkin(design, extra);
  else {
    skin = bootstrapSkin(variant, design, extra);
    out.set('theme.css', bootstrapTheme(variant, design));
  }
  for (const [name, html] of renderPages(m, skin, {
    banner: VARIANT_HTML,
    ...(design.app.name ? { appName: design.app.name } : {}),
    ...(logo ? { logo } : {}),
  }))
    out.set(name, html);
  out.set('state.css', asset('state.css'));
  out.set('app.js', asset('app.js'));
  const stamp: VariantStamp = { variant, manifest: buildManifest(m).hash };
  out.set(VARIANT_FILE, JSON.stringify(stamp, null, 2) + '\n');
  return out;
}

export interface VariantFinding {
  variant: string;
  file: string;
  kind: 'missing-page' | 'extra-page' | 'missing-element' | 'extra-element' | 'stale' | 'unstamped';
  message: string;
}

/** Variant folders under prototype/: every folder with pages or a stamp. */
export function listVariants(root: string): string[] {
  const dir = join(root, VARIANTS_DIR);
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

/**
 * Compare a variant with the generic prototype of the current spec: every page and every `data-src` marker must
 * be there, nothing may be added, and the stamp must match the current manifest.
 */
export function checkVariant(model: SpecModel, root: string, variant: string): VariantFinding[] {
  const dir = join(root, VARIANTS_DIR, variant);
  const manifest = buildManifest(buildPrototype(model));
  const out: VariantFinding[] = [];
  const add = (file: string, kind: VariantFinding['kind'], message: string) =>
    out.push({ variant, file: `${VARIANTS_DIR}/${variant}/${file}`, kind, message });

  const expected = new Map(Object.entries(manifest.screens));
  for (const [id, s] of expected) {
    const path = join(dir, s.file);
    if (!existsSync(path)) {
      add(s.file, 'missing-page', `no page for ${id}`);
      continue;
    }
    const found = collectElements(readFileSync(path, 'utf8'));
    const have = new Set(found);
    const want = new Set(s.elements);
    for (const e of s.elements) if (!have.has(e)) add(s.file, 'missing-element', `missing ${e}`);
    for (const e of found) if (!want.has(e)) add(s.file, 'extra-element', `${e} is not in the spec`);
  }
  if (!existsSync(join(dir, 'index.html'))) add('index.html', 'missing-page', 'no overview page');
  if (existsSync(dir)) {
    const pages = new Set([...expected.values()].map((s) => s.file));
    for (const f of readdirSync(dir).sort()) {
      if (/^SCR-.*\.html$/.test(f) && !pages.has(f)) add(f, 'extra-page', `${f} is not a screen in the spec`);
    }
  }

  const stampPath = join(dir, VARIANT_FILE);
  if (!existsSync(stampPath)) {
    add(VARIANT_FILE, 'unstamped', 'not stamped; build it, or run `prototype check --stamp` once it passes');
  } else {
    const stamp = JSON.parse(readFileSync(stampPath, 'utf8')) as VariantStamp;
    if (stamp.manifest !== manifest.hash)
      add(VARIANT_FILE, 'stale', 'built from an older spec; build it again (or update it and re-stamp)');
  }
  return out;
}

export const stampFor = (model: SpecModel, variant: string): VariantStamp => ({
  variant,
  manifest: buildManifest(buildPrototype(model)).hash,
});

export const isBuiltVariant = (v: string): v is BuiltVariant =>
  (BUILT_VARIANTS as readonly string[]).includes(v);
