import type { Design } from '../../schemas/design.js';
import type { Skin } from '../render.js';
import { CDN, rgb, stylesheet } from './cdn.js';

type Kind = 'bootstrap' | 'tabler';

/** Bootstrap and Tabler share Bootstrap's markup; Tabler uses its own variable prefix and muted-text class. */
export function bootstrapSkin(kind: Kind, design: Design, extraHead: string[]): Skin {
  const muted = kind === 'tabler' ? 'text-secondary' : 'text-body-secondary';
  const sidebar = design.shell === 'sidebar';
  return {
    ...(design.theme.dark ? { html: 'data-bs-theme="dark"' } : {}),
    head: [stylesheet(CDN[kind]), '<link rel="stylesheet" href="theme.css">', ...extraHead],
    shell: design.shell,
    cls: {
      body: kind === 'tabler' ? 'antialiased' : '',
      top: 'navbar bg-body-tertiary border-bottom px-3 gap-3',
      app: 'navbar-brand fw-semibold d-flex align-items-center gap-2',
      badge: 'badge bg-body-secondary text-body border fw-normal',
      role: 'd-flex align-items-center gap-2 mb-0 small',
      'role-select': 'form-select form-select-sm w-auto',
      layout: sidebar ? 'd-flex' : '',
      nav: sidebar ? 'border-end p-3 small' : 'border-bottom px-3 py-2 d-flex flex-wrap gap-4 small',
      'nav-heading': `text-uppercase ${muted} small fw-semibold ${sidebar ? 'mt-3 mb-1' : 'my-0 align-self-center'}`,
      'nav-list': sidebar ? 'nav flex-column' : 'nav gap-2',
      'nav-item': 'nav-item',
      'nav-link': 'nav-link px-0 py-1',
      'nav-link-active': 'nav-link px-0 py-1 active fw-semibold',
      main: 'flex-grow-1 p-4',
      crumb: `${muted} small mb-1`,
      title: 'h3 mb-2',
      purpose: muted,
      meta: `d-flex flex-wrap gap-4 small ${muted} mb-2`,
      gap: 'alert alert-warning py-1 px-2 small mb-2',
      bar: 'd-flex flex-wrap gap-2 align-items-center my-3 small',
      'state-button': 'btn btn-sm btn-outline-secondary',
      action: 'btn btn-primary',
      state: 'alert alert-secondary',
      group: 'card card-body mb-3',
      'group-title': 'h5 card-title',
      mode: `small fw-normal ${muted} ms-1`,
      table: 'table table-sm table-hover mb-0',
      field: 'mb-3',
      label: 'form-label',
      input: 'form-control',
      select: 'form-select',
      check: 'form-check-input',
      req: 'text-danger',
      dialog: 'border rounded-3 p-4 shadow',
      button: 'btn btn-secondary',
      index: 'list-unstyled',
      'section-title': 'h5 mt-4',
    },
  };
}

/** Theme colours, font and radius mapped onto the design system's CSS variables, plus layout glue. */
export function bootstrapTheme(kind: Kind, design: Design): string {
  const p = kind === 'tabler' ? '--tblr' : '--bs';
  const t = design.theme;
  const vars: string[] = [];
  for (const name of ['primary', 'secondary', 'success', 'danger', 'warning'] as const) {
    const c = t[name];
    if (!c) continue;
    vars.push(`  ${p}-${name}: ${c};`, `  ${p}-${name}-rgb: ${rgb(c)};`);
    if (kind === 'tabler') vars.push(`  ${p}-${name}-fg: #fff;`);
  }
  if (t.primary) vars.push(`  ${p}-link-color: ${t.primary};`, `  ${p}-link-color-rgb: ${rgb(t.primary)};`);
  if (t.font) vars.push(`  ${p}-body-font-family: ${t.font};`, `  ${p}-font-sans-serif: ${t.font};`);
  if (t.radius) vars.push(`  ${p}-border-radius: ${t.radius};`);
  const button =
    kind === 'bootstrap' && t.primary
      ? [
          '.btn-primary {',
          ...['bg', 'border-color', 'hover-bg', 'hover-border-color', 'active-bg', 'active-border-color'].map(
            (v) => `  --bs-btn-${v}: ${t.primary};`,
          ),
          '}',
        ]
      : [];
  return [
    '/* Generated by `alterspec prototype build` from design/design.yaml. Put your own overrides in design/tokens.css. */',
    ...(vars.length ? [':root,', '[data-bs-theme] {', ...vars, '}'] : []),
    ...button,
    '.as-nav { flex: 0 0 240px; }',
    '.as-logo { height: 28px; }',
    '.as-meta ul { display: inline; margin: 0; padding: 0; list-style: none; }',
    '.as-meta li { display: inline; margin-right: 0.5rem; }',
    '.as-dl { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1.5rem; margin: 0; }',
    '.as-dl div { display: contents; }',
    '.as-dl dd { margin: 0; }',
    `.as-state-button[aria-pressed='true'] { background: var(${p}-secondary); border-color: var(${p}-secondary); color: #fff; }`,
    '.as-dialog { max-width: 520px; }',
    '',
  ].join('\n');
}
